name: Manually Triggered Dialogflow Restore

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to restore Dialogflow CX agent from'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - main

jobs:
  restore_dialogflow_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected branch
        run: "echo 'Restoring from branch: ${{ github.event.inputs.branch }}'"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Restore Agent from Git
        run: |
          LOCATION="global"
          BRANCH="${{ github.event.inputs.branch }}"
          curl -X POST \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            -H "Content-Type: application/json" \
            "https://${LOCATION}-dialogflow.googleapis.com/v3/projects/${{ secrets.PROJECT_ID }}/locations/${LOCATION}/agents/${{ secrets.AGENT_ID }}:restore" \
            -d "{
              \"gitSource\": {
                \"trackingBranch\": \"${BRANCH}\"
              }
            }"
