name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
  push:
    branches:
      - '**'
    
jobs:
  pr_workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Example Step
        run: |
          echo "PR was created or updated"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR title: ${{ github.event.pull_request.title }}"

      # Add your additional workflow steps here
      
      - name: Notify PR status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const message = `Workflow completed with status: ${context.job.status}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });