name: Restore Agent
on:
  repository_dispatch:
    types: [trigger_restore]
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to restore from'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - develop

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Restore Agent
        run: |
          LOCATION="global"
          BRANCH="${{ github.event.inputs.target_branch || github.event.client_payload.branch }}"
          curl -X POST \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            -H "Content-Type: application/json" \
            "https://${LOCATION}-dialogflow.googleapis.com/v3/projects/${{ secrets.DEV_PROJECT_ID }}/locations/${LOCATION}/agents/${{ secrets.DEV_AGENT_ID }}:restore" \
            -d "{
              \"gitSource\": {
                \"trackingBranch\": \"${BRANCH}\"
              }
            }"
