name: Trigger Restore on PR Merge into Develop

on:
  pull_request_target:
    types: [closed]
    branches: [develop]

jobs:
  trigger_restore:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Restore Workflow via Dispatch
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Personal Access Token with repo scope
        run: |
          BRANCH="${{ github.event.pull_request.base.ref }}"
          ESCAPED_BRANCH=$(echo "$BRANCH" | jq -R .)
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d "{
              \"event_type\": \"trigger_restore\",
              \"client_payload\": {
                \"branch\": $ESCAPED_BRANCH
              }
            }"
